### ISSUE TITLE
Error when setting to 'optional' or 'try' and default strategy

### ISSUE THREAD

**Issue by mattlenz** [dwyl/hapi-auth-jwt2#137]
Thanks for the great work, I'm interested in incorporating this into an app, however I've run into a roadblock.

Hapi does not start when using hapi-auth-jwt2 as the auth strategy and setting it to 'optional' or 'try'.

Can be reproduced wih the example in this repo;

Edit `examples/server.js` and set the strategy to 'optional' or 'try';

```
server.auth.strategy('jwt', 'jwt', 'optional',
{ key: secret, validateFunc: validate,
  verifyOptions: { ignoreExpiration: true }
});
```

Error:

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IkFudGhvbnkgVmFsaWQgVXNlciIsImlhdCI6MTQ1MjY4NTgyMX0.d3Ua9Xccivamw34un3QO5_p5iN78S8QKLt9_DFnWAcQ
hapi-auth-jwt2/node_modules/hapi/node_modules/hoek/lib/index.js:732
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Cannot set default strategy more than once
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (hapi-auth-jwt2/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
    at internals.Auth.default (hapi-auth-jwt2/node_modules/hapi/lib/auth.js:77:10)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin._applyChild (hapi-auth-jwt2/node_modules/hapi/lib/plugin.js:587:19)
    at Object.auth.default (hapi-auth-jwt2/node_modules/hapi/lib/plugin.js:64:18)
    at hapi-auth-jwt2/example/server.js:49:22
    at hapi-auth-jwt2/node_modules/hapi/lib/plugin.js:326:16
    at done (hapi-auth-jwt2/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Object.exports.register (hapi-auth-jwt2/lib/index.js:10:3)
    at Object.target [as register] (hapi-auth-jwt2/node_modules/hapi/node_modules/joi/lib/object.js:80:30)
    at each (hapi-auth-jwt2/node_modules/hapi/lib/plugin.js:320:14)/
```

node 5.2.0
hapi-auth-jwt 5.3.2

Any ideas? The readme does indicate optional/try are supported, however it does not seem to work for me.

**Comment by mattlenz** [comment]
Hi, just an update. Looks like the plugin works correctly after removing `server.auth.default('jwt')`, however this means you need to set `auth: 'jwt'` for each of your routes by hand.

**Comment by nelsonic** [comment]
hi @mattlenz was your app already setting the `default` strategy?

**Comment by mattlenz** [comment]
Hi @nelsonic -- No default strategy is set elsewhere, and I've gotten the same error by running the examples.

However I've found that I can get by without setting the default strategy, so feel free to close this if there is no issue, thanks for your time!

**Comment by iteles** [comment]
Hi @mattlenz :blush: 

Firstly, thanks for raising the issue - it's always helpful to us and people who might come across this when using the plugin!

If this is no longer an issue for you, would you mind closing it? We always prefer for the person who opened the issue to close it when their issue is resolved if possible :+1: 

Thanks again!
