### ISSUE TITLE
HTTP500 in error message with accent errorFunc

### ISSUE THREAD

**Issue by abelmferreira** [dwyl/hapi-auth-jwt2#250]
I'm customizing error messages and when I put text with accents, the function returns error 500

```
  server.auth.strategy('jwt', 'jwt', {
    key: 'mySecret',
    validateFunc: ValidateAuthFunction,
    verifyOptions: {algorithms: [ 'HS256' ]},
    headerKey: 'authorization',
    urlKey: false,
    errorFunc: AuthMessagesFunction
  })
```

This is my function

```
function AuthMessagesFunction (err) {
  if (err.message === 'Invalid token') err.message = 'Token Inválido'
  if (err.message === 'Invalid credentials') err.message = 'Token expirado'
  if (err.message === null) err.message = 'Header inválido'
  return err
}
```

With the accent á in "Inválido" word the function returns error 500 and the below trace, just removing the accent everything works great

```
Debug: internal, implementation, error
    Error: Uncaught error: Bad attribute value (Token inválido)
    at Object.exports.assert (/node_modules/hapi-auth-jwt2/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.escapeHeaderAttribute (/node_modules/hapi-auth-jwt2/node_modules/hoek/lib/index.js:829:13)
    at Object.exports.unauthorized (/node_modules/hapi-auth-jwt2/node_modules/boom/lib/index.js:237:67)
    at raiseError (/node_modules/hapi-auth-jwt2/lib/index.js:95:28)
    at /node_modules/hapi-auth-jwt2/lib/index.js:155:34
    at /node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by nelsonic** [comment]
@abelmferreira which version of Hapi are you using?

**Comment by abelmferreira** [comment]
@nelsonic its a new project with the last stable 16.6.2

**Comment by FilWisher** [comment]
HTTP headers generally have to be ASCII but you have used a unicode symbol.

This is enforced by hoek [here](https://github.com/hapijs/hoek/blob/3c80a87fe51a1d3163c5cd805b7c9d323eb51587/lib/index.js#L812).

**Comment by nelsonic** [comment]
@abelmferreira as noted by Will, HTTP Headers should be ASCII-only characters. Closing as 3 years old.
