### ISSUE TITLE
Updated hapijs to 17.2.0 using h-a-jwt2 7.3.0, and got this error.

### ISSUE THREAD

**Issue by Kuchiriel** [dwyl/hapi-auth-jwt2#258]
```
(node:13741) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": function (server, options, next) {\n  server.auth.scheme('jwt', internals.implementation); // hapijs.com/api#serverauthapi\n\n  return next();\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at Object.exports.apply (/home/trevor/Projects/Zion ERP/backend/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/home/trevor/Projects/Zion ERP/backend/node_modules/hapi/lib/server.js:384:31)
    at _callee$ (/home/trevor/Projects/Zion ERP/backend/src/server.js:15:14)
    at tryCatch (/home/trevor/Projects/Zion ERP/backend/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/trevor/Projects/Zion ERP/backend/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/trevor/Projects/Zion ERP/backend/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/trevor/Projects/Zion ERP/backend/src/server.js:19:191)
    at /home/trevor/Projects/Zion ERP/backend/src/server.js:19:437
    at new Promise (<anonymous>)
    at /home/trevor/Projects/Zion ERP/backend/src/server.js:19:99
(node:13741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nelsonic** [comment]
Hi @Kuchiriel, `hapi-auth-jwt2@v7.3.0` is _not_ compatible with Hapi v.17 
(_neither is `hapi-auth-jwt2@v7.4.0` for that matter_).

We will be releasing `hapi-auth-jwt2@v8.0.0` "_soon_" based which _will_ be Hapi v.17 compatible.
Thank you for your patience. 👍

**Comment by Kuchiriel** [comment]
Hi @nelsonic, thanks!

**Comment by SimonSchick** [comment]
Fyi, hapi 17 typings have been released!

**Comment by jaulz** [comment]
@nelsonic great news! Do you have any timeline for this? Do you need help?

**Comment by Kuchiriel** [comment]
@nelsonic 
I am using "hapi": "^17.5.4" and "hapi-auth-jwt2": "^8.1.0",
And I keep getting the same error :/

**Comment by Kuchiriel** [comment]
@SimonSchick Okay

**server.js**
```
import routes from './routes'
import plugins from './plugins'

import {
  getSecret,
  Validate
} from './jwt'

import {
  Server
} from 'hapi'

const init = async() => {

  const server = await new Server({
    routes: {
      cors: true
    },
    port: 5000
  })

  // await server.connection()

  await server.register(plugins)

  await server.auth.strategy('jwt', 'jwt', {
    allowMultipleHeaders: true,
    key: await getSecret(),
    validateFunc: await Validate(),
    verifyOptions: {
      algorithms: ['HS256']
    }
  })

  await server.auth.default('jwt')

  await server.on('request-error', (req, err) => {
    console.error('[server]', err) // eslint-disable-line
  })

  await server.on('start', (req, err) => {
    if (err) {
      console.error('[server]', err) // eslint-disable-line
    } else {
      console.log('[server] started') // eslint-disable-line
    }
  })

  await server.on('stop', (req, err) => {
    if (err) {
      console.error('[server]', err) // eslint-disable-line
    } else {
      console.log('[server] stoped') // eslint-disable-line
    }
  })

  await server.route(routes(server))

  await server.start(err => {
    if (err) {
      throw err
    }
    console.log(`[server] Running at: ${server.info.uri}`) // eslint-disable-line
  })

}

init()
  .then((res) => console.log('[server] All the Plugins are added', res)) // eslint-disable-line
  .catch((err) => console.error('[server] Server Error', err)) // eslint-disable-line
```
**plugins.js**

```
import Jwt2 from 'hapi-auth-jwt2'
import Pgc from 'hapi-postgres-connection'


const Blipp = {
  register: require('blipp'),
  options: {
    showAuth: true
  }
}
export default [
  Jwt2,
  Pgc,
  Blipp
]
```

**Comment by SimonSchick** [comment]
I don't know what runtime/transpiler you are using but `default` import/exports are not the same as `require` return values, please double check the datastructures you are passing.

**Comment by Kuchiriel** [comment]
@SimonSchick Already tried with _require_, with no success.

**Comment by Kuchiriel** [comment]
@nelsonic I've downgraded and tested the deps one by one and I've managed to make it work. I will comment here for anyone with the same issue after upgrading hapi.js and hapi.js plugins.

* "blipp": "^2.3.0",
* "boom": "^5.2.0",
* "good": "^7.2.0",
* "good-console": "^6.4.0",
* "good-squeeze": "^5.0.2",
* "hapi": "^16.5.2",
* "hapi-auth-jwt2": "^7.3.0",
* "hapi-cors": "^1.0.1",
* "hapi-postgres-connection": "^6.2.0",
* "joi": "^10.6.0",

The problem seens to be, the newer versions of hapi.js and newers plugins don't work properly with es2018 code style.

**Comment by Dindaleon** [comment]
any updates on this? I have hapi-auth-jwt2 v8.4.0 still not wroking.
