### ISSUE TITLE
Simple example is not working

### ISSUE THREAD

**Issue by jamalsoueidan** [dwyl/hapi-auth-jwt2#285]
Hello,

I'm creating a simple example with hapi-auth-jwt2 and its not working, im getting this error whenever I send GET request through POSTMAN with a token, if there is no token it get the right message about Missing authentication.

```
Debug: internal, implementation, error
    TypeError: Cannot destructure property `key` of 'undefined' or 'null'.
    at Object.authenticate (C:\Users\Jamal\reactjs\shopify-express-application\node_modules\hapi-auth-jwt2\lib\index.js:151:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
C:\Users\Jamal\reactjs\shopify-express-application\node_modules\jwks-rsa\lib\integrations\hapi.js:63
      return cb(null, key.publicKey || key.rsaPublicKey, key);
             ^

TypeError: cb is not a function
    at C:\Users\Jamal\reactjs\shopify-express-application\node_modules\jwks-rsa\lib\integrations\hapi.js:63:14
    at C:\Users\Jamal\reactjs\shopify-express-application\node_modules\lru-memoizer\index.js:81:20
    at Array.forEach (<anonymous>)
    at C:\Users\Jamal\reactjs\shopify-express-application\node_modules\lru-memoizer\index.js:77:17
    at C:\Users\Jamal\reactjs\shopify-express-application\node_modules\jwks-rsa\lib\wrappers\cache.js:26:16
    at C:\Users\Jamal\reactjs\shopify-express-application\node_modules\jwks-rsa\lib\JwksClient.js:58:18
    at C:\Users\Jamal\reactjs\shopify-express-application\node_modules\jwks-rsa\lib\JwksClient.js:126:16
    at Request._callback (C:\Users\Jamal\reactjs\shopify-express-application\node_modules\jwks-rsa\lib\JwksClient.js:94:16)
    at Request.self.callback (C:\Users\Jamal\reactjs\shopify-express-application\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
```

My code is very straight forward, not special.

```javascript
'use strict';

const Hapi = require('hapi');
const hapiJwt = require('hapi-auth-jwt2');
const token = require('jsonwebtoken');
const jwksRsa = require('jwks-rsa');

const server = new Hapi.Server({
  port: 3000,
  host: 'localhost'
});

const validate = async (decoded, request) => {
  if (decoded && decoded.sub) {
     return { isValid: true };
  }
  return { isValid: false };
};

const registerRoutes = () => {
  server.route({
    method: 'GET',
    path: '/api/public',
    config: {
      auth: false,
      handler: (req) => {
        return token.sign({scope: "admin"}, "process.env.JWT_SECRET");
      }
    }
  });

  // This route need authentication
  server.route({
    method: 'GET',
    path: '/api/private',
    config: {
      auth: 'jwt',
      handler: (req) => {
        return "lets go"
      }
    }
  });
}

const init = async() => {
  await server.register(hapiJwt);
  // see: http://Hapi.com/api#serverauthschemename-scheme
  server.auth.strategy('jwt', 'jwt', {
    complete: true,
    key: jwksRsa.hapiJwt2Key({
      cache: true,
      rateLimit: true,
      jwksRequestsPerMinute: 5,
      jwksUri: `https://givettilbud.eu.auth0.com/.well-known/jwks.json`
    }),
    verifyOptions: {
      audience: '/api/v2/',
      issuer: `https://givettilbud.eu.auth0.com/`,
      algorithms: ['RS256']
    },
    validate: validate
  });

  server.auth.default('jwt');

  registerRoutes();

  await server.start();
  return server;

};

init().then(server => {
  console.log('Server running at:', server.info.uri);
}).catch(err => {
  console.log(err);
});
```

I'm using the following versions.

```javascript
{
  "name": "shopify-express-application",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cookie": "^0.3.1",
    "dotenv": "^6.1.0",
    "hapi": "^17.6.0",
    "hapi-auth-jwt2": "^8.1.0",
    "jsonwebtoken": "^8.3.0",
    "jwks-rsa": "^1.3.0",
    "request": "^2.88.0",
    "request-promise": "^4.2.2"
  },
  "devDependencies": {
    "nodemon": "^1.18.4"
  }
}
```

I hope someone can see where I'm making a mistake.

**Comment by mariuslazar93** [comment]
Check this gist for a workaround: https://gist.github.com/sergioalvz/fe1388096f06097f0b82c800369adbff

**Comment by nelsonic** [comment]
@jamalsoueidan did you try the async version?
