### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by tinkeshwar** [dwyl/hapi-auth-jwt2#363]
can anyone help me with the issue, I am getting error 500 for invalid and expired token instead of 401, here is my code, I have tried everything:

```
import Hapi from '@hapi/hapi';
import Boom from '@hapi/boom';
import * as env from './environment';
import documentor from './documentor';
import routes from './route';
import logger from './logger';
import AuthService from '../services/auth/AuthService';
import Joi from 'joi';
import Redis from 'ioredis';
// initialize configuration
env.config();
const {SERVER_PORT,SERVER_HOST,JWT_TOKEN} = process.env;

export const server = new Hapi.Server({
    host:SERVER_HOST,
    port:SERVER_PORT,
    routes: {
        cors: {
            origin: ['*'],
            credentials: true,
            headers: ['Accept', 'Content-Type','Authorization'],
            additionalHeaders: ['X-localization']
        },
        validate: {
            failAction: async (request, h, err) => {
                if (process.env.NODE_ENV === 'production') {
                    throw Boom.badRequest(err.message);
                } else {
                    throw Boom.badRequest(err.message);
                }
            }
        }
    }
});

let prepared = false;
const redis = new Redis();

const prepare = async (): Promise<void> => {
    if(prepared){
        return;
    }
    await server.register(documentor as any);
    server.auth.strategy('token','jwt',{
        key:JWT_TOKEN,
        validate: AuthService.verify
    });
    server.validator(Joi);
    server.route(routes);
    prepared = true;
}

export const start = async (): Promise<Hapi.Server> => {
    await prepare();
    await server.start();
    logger.info(`Redis is ${redis.status}`);
    logger.info(`Server started on port: ${SERVER_PORT}`);
    logger.info(`Explorer is available at: ${SERVER_HOST}:${SERVER_PORT}/explorer`);
    return server;
}

export const init = async (): Promise<Hapi.Server> => {
    await prepare();
    await server.initialize();
    return server;
}

export const stop = async (): Promise<void> => {
    await server.stop();
}

**Comment by tinkeshwar** [comment]
Error i am getting;

Debug: auth, unauthenticated, error, token 
    Error: Expired token
    at Object.raiseError (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/hapi-auth-jwt2/lib/index.js:302:45)
    at Object.internals.authenticate (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/hapi-auth-jwt2/lib/index.js:171:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.authenticate (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/hapi-auth-jwt2/lib/index.js:353:22)
    at exports.Manager.execute (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at module.exports.internals.Auth._authenticate (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/@hapi/hapi/lib/auth.js:258:30)
    at Request._lifecycle (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/@hapi/hapi/lib/request.js:372:32)
    at Request._execute (/Users/tinkeshwar/Sites/vidhyasaga/tool/node_modules/@hapi/hapi/lib/request.js:280:9)
Debug: internal, error 
    ValidationError: "attributes" is not allowed

**Comment by tinkeshwar** [comment]
hapi-auth-jwt2/lib/index.js --->  line number --> 302 ---->
`const error = Boom[errorContext.errorType](
    errorContext.message,
    errorContext.scheme,
    errorContext.attributes
  );`

Debug: internal, error ValidationError: "attributes" is not allowed
